export const data = [
    {
        id: 0,
        name: "Palm Harbour",
        address: "5314 Park Lk, San Antonio, TX 78244",
        location: "San Antonio, Texas",
        url: "https://maps.googleapis.com/maps/api/streetview?channel=rdc-streetview&client=gme-movesalesinc&size=640x480&location=19360+Murray+Hill+St%2CDetroit%2CMI%2C48235&signature=KDmlbkncYjq4jvYNDHe7PdHXRf4",
        no_beds: 4,
        no_baths: 2,
        lot_size: 1539,
        type: "Single Family",
        move_in_date: new Date("02/15/2022"),
        rent: 1695,
        like: false
    },
    {
        id: 1,
        name: "Bexar Harbour",
        address: "6834 Indian Lake Dr, San Antonio, TX 78244",
        location: "San Antonio, Texas",
        url: "https://thumbs.dreamstime.com/b/new-house-4623668.jpg",
        no_beds: 4,
        no_baths: 2,
        lot_size: 1448,
        type: "Single Family",
        move_in_date: new Date("02/27/2022"),
        rent: 1349,
        like: false
    },
    {
        id: 2,
        name: "Homebour",
        address: "5519 Roanwood, San Antonio, TX 78244",
        location: "San Antonio, Texas",
        url: "https://thumbs.dreamstime.com/b/modern-house-exterior-brick-walls-garden-chain-link-fence-96936176.jpg",
        no_beds: 4,
        no_baths: 3,
        lot_size: 1589,
        type: "Single Family",
        move_in_date: new Date("01/17/2022"),
        rent: 1400,
        like: false
    },
    {
        id: 3,
        name: "Bourino",
        address: "6907 Twin Lake Dr, San Antonio, TX 78244",
        location: "San Antonio, Texas",
        url: "https://thumbs.dreamstime.com/b/kerikeri-new-zealand-38210671.jpg",
        no_beds: 4,
        no_baths: 2,
        lot_size: 1352,
        type: "Single Family",
        move_in_date: new Date("03/01/2022"),
        rent: 1190,
        like: false
    },
    {
        id: 4,
        name: "Peritorico",
        address: "6919 Moon Lake Dr, San Antonio, TX 78244",
        location: "San Antonio, Texas",
        url: "https://thumbs.dreamstime.com/b/settlers-village-48438.jpg",
        no_beds: 3,
        no_baths: 2,
        lot_size: 1329,
        type: "Single Family",
        move_in_date: new Date("02/14/2022"),
        rent: 1250,
        like: false
    },
    {
        id: 5,
        name: "Babel",
        address: "6919 Moon Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/replica-melaka-s-sultante-palace-malacca-malaysia-40675706.jpg",
        no_beds: 4,
        no_baths: 2,
        lot_size: 1729,
        type: "Double Family",
        move_in_date: new Date("04/14/2022"),
        rent: 2057,
        like: false
    },
    {
        id: 6,
        name: "Hamilo",
        address: "8979 Salt Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/royal-palace-5889512.jpg",
        no_beds: 4,
        no_baths: 3,
        lot_size: 1929,
        type: "Double Family",
        move_in_date: new Date("02/14/2022"),
        rent: 2587,
        like: false
    },
    {
        id: 7,
        name: "Beverly Homes",
        address: "7919 Moon Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/french-quarter-pondicherry-india-french-quarter-pondicherry-india-144692167.jpg",
        no_beds: 4,
        no_baths: 2,
        lot_size: 1529,
        type: "Double Family",
        move_in_date: new Date("01/13/2022"),
        rent: 2057,
        like: false
    },
    {
        id: 8,
        name: "Springfield",
        address: "6919 Moon Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/new-england-road-trip-fall-usa-dorset-vermont-october-st-exterior-colony-house-cold-day-town-172026907.jpg",
        no_beds: 3,
        no_baths: 3,
        lot_size: 1500,
        type: "Double Family",
        move_in_date: new Date("04/11/2022"),
        rent: 1851,
        like: false
    },
    {
        id: 9,
        name: "Faulker",
        address: "5999 Sunn Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/kerikeri-new-zealand-38210671.jpg",
        no_beds: 3,
        no_baths: 2,
        lot_size: 1629,
        type: "Double Family",
        move_in_date: new Date("04/14/2022"),
        rent: 1693,
        like: false
    },
    {
        id: 10,
        name: "Ave Holmes",
        address: "5999 Jupitor Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://thumbs.dreamstime.com/b/housing-estate-link-house-2660912.jpg",
        no_beds: 2,
        no_baths: 2,
        lot_size: 1229,
        type: "Bachelor/single",
        move_in_date: new Date("06/18/2022"),
        rent: 1293,
        like: false
    },
    {
        id: 11,
        name: "Sevilla",
        address: "5999 Neptune Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&w=1000&q=80",
        no_beds: 1,
        no_baths: 1,
        lot_size: 1029,
        type: "Bachelor/single",
        move_in_date: new Date("07/18/2022"),
        rent: 729,
        like: false
    },
    {
        id: 12,
        name: "Ave Holmes",
        address: "5999 Pluto Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://images.adsttc.com/media/images/6040/f47f/f91c/811a/2800/00dd/newsletter/_8.0.jpg?1614869564",
        no_beds: 2,
        no_baths: 2,
        lot_size: 1229,
        type: "Bachelor/single",
        move_in_date: new Date("06/18/2022"),
        rent: 1293,
        like: false
    },
    {
        id: 13,
        name: "Greenery Holmes",
        address: "5999 Jupitor Lake Dr,Boston, USA",
        location: "Boston, USA",
        url: "https://www.readysteadysell.co.uk/wp-content/uploads/2021/09/link-detached-house.jpg",
        no_beds: 1,
        no_baths: 1,
        lot_size: 1029,
        type: "Bachelor/single",
        move_in_date: new Date("04/23/2022"),
        rent: 1293,
        like: false
    },
    {
        id: 14,
        name: "Woodland Holmes",
        address: "5799 Neptune Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&w=1000&q=80",
        no_beds: 2,
        no_baths: 2,
        lot_size: 1229,
        type: "Bachelor/single",
        move_in_date: new Date("03/18/2022"),
        rent: 1293,
        like: false
    },
    {
        id: 15,
        name: "Highlands House",
        address: "5799 Neptune Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://thumbs.dreamstime.com/b/kerikeri-new-zealand-38210671.jpg",
        no_beds: 1,
        no_baths: 1,
        lot_size: 1309,
        type: "Bachelor/single",
        move_in_date: new Date("04/21/2022"),
        rent: 1193,
        like: false
    },
    {
        id: 16,
        name: "Madlane manue",
        address: "5799 Neptune Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://maps.googleapis.com/maps/api/streetview?channel=rdc-streetview&client=gme-movesalesinc&size=640x480&location=19360+Murray+Hill+St%2CDetroit%2CMI%2C48235&signature=KDmlbkncYjq4jvYNDHe7PdHXRf4",
        no_beds: 1,
        no_baths: 1,
        lot_size: 1339,
        type: "Bachelor/single",
        move_in_date: new Date("05/18/2022"),
        rent: 1593,
        like: false
    },
    {
        id: 17,
        name: "Grandy base",
        address: "5799 Neptune Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://thumbs.dreamstime.com/b/french-quarter-pondicherry-india-french-quarter-pondicherry-india-144692167.jpg",
        no_beds: 4,
        no_baths: 3,
        lot_size: 1829,
        type: "Double Family",
        move_in_date: new Date("03/18/2022"),
        rent: 2593,
        like: false
    },
    {
        id: 18,
        name: "Aurora ",
        address: "5799 planet nine Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://thumbs.dreamstime.com/b/kerikeri-new-zealand-38210671.jpg",
        no_beds: 4,
        no_baths: 3,
        lot_size: 1229,
        type: "Single Family",
        move_in_date: new Date("03/18/2022"),
        rent: 2793,
        like: false
    },
    {
        id: 19,
        name: "Avenue grand villa",
        address: "5799 Saturn Lake Dr, Boston, USA",
        location: "Boston, USA",
        url: "https://thumbs.dreamstime.com/b/replica-melaka-s-sultante-palace-malacca-malaysia-40675706.jpg",
        no_beds: 5,
        no_baths: 5,
        lot_size: 2229,
        type: "Villa",
        move_in_date: new Date("03/11/2022"),
        rent: 3500,
        like: false
    },
    {
        id: 20,
        name: "Sunny enclave",
        address: "5799 Saturn Lake Dr, New York, USA",
        location: "New York, USA",
        url: "https://thumbs.dreamstime.com/b/replica-melaka-s-sultante-palace-malacca-malaysia-40675706.jpg",
        no_beds: 3,
        no_baths: 2,
        lot_size: 1529,
        type: "Single Family",
        move_in_date: new Date("04/21/2022"),
        rent: 2500,
        like: false
    },
]